//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuralBot.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RuralDB : DbContext
    {
        public RuralDB()
            : base("name=RuralDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casas> Casas { get; set; }
        public virtual DbSet<Lugares> Lugares { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
